services:
  mitsuba3_playground:
    container_name: mitsuba3_playground
    init: true
    shm_size: 8gb

    build:
      context: .
    environment:
      # By default, use the Mitsuba's official repo and stable branch.
      # To override these, add them to an .env file.
      - GITHUB_USER=${GITHUB_USER:-mitsuba-renderer}
      - MITSUBA_REF=${MITSUBA_REF:-stable}
      # Required for compiling Mitsuba.
      - CC=clang-18
      - CXX=clang++-18
      # For UV virtual environment.
      - UV_LINK_MODE=copy
      - VIRTUAL_ENV=/workspace/.venv
      # This is to easily import src in the notebooks.
      - PYTHONPATH=/workspace/src

    # Add GPU support.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    volumes:
        # Mount the source directory in the container.
      - type: bind
        source: ..
        target: /workspace
        # These are named volumes for UV.
      - uv-cache:/root/.cache/uv
      - uv-venv-mitsuba3_playground:/workspace/.venv
      - uv-python-installs:/root/.local/share/uv/python  # Cache Python installations.

    ports:
      - "2719:2719"  # Marimo.

    # Startup command.
    stdin_open: true
    tty: true
    entrypoint: ["bash", "/workspace/docker/entrypoint.sh"]
    command: tail -f /dev/null

volumes:
  uv-cache:
  uv-venv-mitsuba3_playground:
  uv-python-installs:
